# Github workflow to compile latex and deploy the pdf to an orphan branch.
# The latest compiled pdf is at available at e.g.
# https://github.com/dgerosa/reponame/blob/build/filename.pdf

name: writetex
on: [push]
env:
      DIR: CV
      FILE: cv_3
steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install texlive-xetex texlive-publishers texlive-science latexmk cm-super
      - name: Install libertine
        run: sudo apt-get update && sudo apt-get install -y fonts-linuxlibertine
      - name: LaTeX compile
        working-directory: ${{ env.DIR }}
        # run: latexmk -pdf -bibtex ${{ env.FILE }}
        run: xelatex -interaction=nonstopmode -halt-on-error ${{ env.FILE }};
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts

